[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"
dependencies = [
    "typer",
]


[project.scripts]
nexus = "{{ cookiecutter.project_slug }}.cli:app"
